In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('weather.csv')

In [3]:
df.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,NaN,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

## Operating on Null Values

As we have seen, Pandas treats ``None`` and ``NaN`` as essentially interchangeable for indicating missing or null values.
To facilitate this convention, there are several useful methods for detecting, removing, and replacing null values in Pandas data structures.
They are:

- ``isnull()``: Generate a boolean mask indicating missing values
- ``notnull()``: Opposite of ``isnull()``
- ``dropna()``: Return a filtered version of the data
- ``fillna()``: Return a copy of the data with missing values filled or imputed

We will conclude this section with a brief exploration and demonstration of these routines.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MinTemp        365 non-null    float64
 1   MaxTemp        364 non-null    float64
 2   Rainfall       366 non-null    float64
 3   Evaporation    366 non-null    float64
 4   Sunshine       363 non-null    float64
 5   WindGustDir    363 non-null    object
 6   WindGustSpeed  364 non-null    float64
 7   WindDir9am     335 non-null    object
 8   WindDir3pm     365 non-null    object
 9   WindSpeed9am   353 non-null    float64
 10  WindSpeed3pm   366 non-null    int64
 11  Humidity9am    363 non-null    float64
 12  Humidity3pm    366 non-null    int64
 13  Pressure9am    366 non-null    float64
 14  Pressure3pm    366 non-null    float64
 15  Cloud9am       366 non-null    int64
 16  Cloud3pm       366 non-null    int64
 17  Temp9am        366 non-null    float64
 18  Temp3pm        366 non-null    float64
 19  RainToday      366 non-null    object
 20  RISK_MM        366 non-null    float64
 21  RainTomorrow   366 non-null    object
dtypes: float64(13), int64(4), object(5)
memory usage: 63.0+ KB

In [5]:
df.shape

(366, 22)

In [9]:
df[df.WindDir9am.isnull()]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
113,12.7,28.6,6.6,3.2,8.6,W,50.0,NaN,W,NaN,...,42,1008.3,1002.3,5,5,16.5,27.4,Yes,0.0,No
118,11.7,27.6,0.0,7.8,8.1,W,48.0,NaN,W,NaN,...,25,1013.6,1009.1,2,6,17.6,26.8,No,0.0,No
127,10.8,29.2,0.0,8.4,7.5,E,50.0,NaN,ENE,NaN,...,34,1021.6,1017.7,0,7,17.5,27.7,No,3.0,Yes
138,12.5,29.9,0.0,5.8,10.7,NW,43.0,NaN,WNW,0.0,...,30,1022.7,1018.8,0,1,16.8,29.2,No,0.0,No
140,11.5,29.3,0.0,5.2,8.0,NW,46.0,NaN,WSW,0.0,...,35,1013.8,1009.4,7,7,17.1,27.6,No,0.0,No
174,7.5,19.0,0.0,4.0,6.8,ENE,26.0,NaN,ESE,0.0,...,43,1025.5,1022.2,6,5,12.6,18.1,No,0.0,No
176,5.0,20.9,0.0,2.0,8.9,WNW,22.0,NaN,NW,0.0,...,42,1019.9,1014.3,7,6,10.1,20.6,No,0.2,No
180,-2.1,13.8,0.2,1.8,9.5,NNW,22.0,NaN,NNW,0.0,...,40,1020.6,1019.6,0,1,6.3,13.2,No,0.0,No
189,-0.2,18.1,0.0,4.4,9.4,NW,24.0,NaN,NW,0.0,...,44,1021.4,1018.9,1,1,6.7,16.9,No,0.0,No
195,2.2,18.6,0.0,2.0,9.2,NNW,31.0,NaN,NNW,NaN,...,44,1024.4,1021.0,1,3,8.5,17.8,No,0.0,No
200,-2.7,18.1,0.0,2.2,9.3,W,52.0,NaN,WNW,0.0,...,36,1017.8,1014.3,1,1,3.5,16.7,No,0.0,No
208,4.9,18.1,5.2,1.2,8.5,NNW,22.0,NaN,NW,0.0,...,55,1025.7,1022.3,1,1,8.9,17.7,Yes,0.0,No
209,1.4,16.8,0.0,1.6,8.2,NW,20.0,NaN,NW,0.0,...,50,1027.2,1024.7,1,4,6.2,16.3,No,0.2,No
212,-0.9,18.5,0.0,2.2,8.9,E,22.0,NaN,N,0.0,...,38,1030.2,1027.4,2,3,4.7,18.2,No,0.0,No
213,0.6,14.0,0.0,2.2,2.7,NE,17.0,NaN,ENE,NaN,...,67,1032.3,1028.9,7,7,4.6,13.9,No,0.0,No
237,4.3,12.6,0.0,2.0,9.0,NW,46.0,NaN,WNW,0.0,...,54,1026.3,1021.9,3,1,7.8,11.3,No,0.0,No
247,-0.1,14.2,0.0,1.4,7.0,W,13.0,NaN,WNW,NaN,...,55,1032.9,1028.9,1,2,4.7,12.6,No,0.0,No
249,3.0,11.1,0.8,1.4,0.2,W,35.0,NaN,N,0.0,...,96,1024.4,1021.1,7,8,6.3,8.6,No,16.8,Yes
250,2.9,9.5,16.8,1.4,6.5,NW,35.0,NaN,NW,0.0,...,72,1021.6,1019.6,6,6,5.5,7.4,Yes,0.0,No
255,0.5,11.0,0.0,1.0,0.9,NNW,31.0,NaN,NW,0.0,...,69,1024.4,1021.9,7,7,2.8,10.7,No,0.0,No
257,-1.7,13.6,0.0,1.8,5.2,NNW,28.0,NaN,NNW,NaN,...,46,1023.0,1020.1,1,7,3.9,13.3,No,0.2,No
259,-1.8,11.5,0.0,0.6,4.7,NNW,41.0,NaN,NNW,0.0,...,55,1019.7,1013.9,7,3,1.3,11.0,No,0.0,No
262,-1.1,11.0,0.2,1.8,0.0,WNW,41.0,NaN,NE,0.0,...,87,1014.4,1009.0,7,8,2.4,8.7,No,19.2,Yes
272,-2.8,12.2,0.0,2.6,8.7,NNW,31.0,NaN,NNW,0.0,...,48,1018.3,1014.6,1,1,2.7,11.5,No,0.0,No
273,-2.8,14.1,0.0,2.2,6.8,WNW,48.0,NaN,WNW,0.0,...,38,1017.3,1012.9,1,7,3.0,12.8,No,1.0,No
278,-1.9,10.9,0.0,1.8,4.2,S,50.0,NaN,SSW,0.0,...,72,1020.8,1019.2,3,8,5.5,7.2,No,4.0,Yes
299,-1.5,17.3,0.0,2.8,9.0,NW,48.0,NaN,WNW,0.0,...,23,1023.9,1020.3,5,7,4.8,15.8,No,0.0,No
302,-0.2,16.2,0.0,3.4,5.9,E,28.0,NaN,ENE,0.0,...,45,1027.6,1022.9,7,6,7.3,14.6,No,0.0,No
312,0.2,15.5,1.0,2.4,9.4,SE,31.0,NaN,WNW,0.0,...,37,1020.6,1018.2,1,1,7.2,15.3,No,0.0,No
351,5.0,24.1,0.0,6.2,12.0,NNW,52.0,NaN,NNW,0.0,...,34,1024.5,1020.7,6,1,11.6,21.9,No,0.0,No
360,7.9,26.1,0.0,6.8,3.5,NNW,43.0,NaN,WNW,0.0,...,20,1017.6,1014.2,5,8,16.3,25.9,No,0.0,No

In [12]:
df['WindDir9am'][df.WindDir9am.isnull()].agg('count')

0

In [13]:
df['WindDir9am']

0       SW
1        E
2        N
3      WNW
4      SSE
      ...
361    SSE
362    NNW
363    ENE
364    SSW
365     NW
Name: WindDir9am, Length: 366, dtype: object

In [16]:
df[df.MinTemp.isnull()]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
9,NaN,22.8,16.2,5.4,7.7,E,31.0,S,ESE,7.0,...,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No

In [23]:
df.MinTemp.head(12)

0      8.0
1     14.0
2     13.7
3     13.3
4      7.6
5      6.2
6      6.1
7      8.3
8      8.8
9      NaN
10     9.1
11     8.5
Name: MinTemp, dtype: float64

In [11]:
df.MinTemp.fillna(method='ffill',inplace=True)

In [12]:
#df['MinTemp'].fillna(method='ffill')

In [13]:
df.MinTemp.head(12)

0      8.0
1     14.0
2     13.7
3     13.3
4      7.6
5      6.2
6      6.1
7      8.3
8      8.8
9      8.8
10     9.1
11     8.5
Name: MinTemp, dtype: float64

In [14]:
df[df.MaxTemp.isnull()]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
6,6.1,NaN,0.2,4.2,8.4,SE,43.0,SE,ESE,NaN,...,47,1024.6,1022.2,4,6,12.4,17.3,No,0.0,No
12,10.1,NaN,0.0,7.2,13.0,WNW,30.0,S,NW,NaN,...,29,1022.0,1017.1,0,1,17.0,27.1,No,0.0,No

In [15]:
df.MaxTemp.head(14)

0     24.3
1     26.9
2     23.4
3     15.5
4     16.1
5     16.9
6      NaN
7     17.0
8     19.5
9     22.8
10    25.2
11    27.3
12     NaN
13    30.9
Name: MaxTemp, dtype: float64

In [16]:
#df.MaxTemp.fillna(method='bfill',inplace=True)

In [17]:
df.MaxTemp.head(14)

0     24.3
1     26.9
2     23.4
3     15.5
4     16.1
5     16.9
6      NaN
7     17.0
8     19.5
9     22.8
10    25.2
11    27.3
12     NaN
13    30.9
Name: MaxTemp, dtype: float64

In [18]:
df.MaxTemp.interpolate(method='linear',inplace=True)

In [24]:
df.MaxTemp.interpolate?

In [19]:
df.MaxTemp.head(14)

0     24.30
1     26.90
2     23.40
3     15.50
4     16.10
5     16.90
6     16.95
7     17.00
8     19.50
9     22.80
10    25.20
11    27.30
12    29.10
13    30.90
Name: MaxTemp, dtype: float64

In [20]:
df.shape

(366, 22)

In [21]:
df.dropna()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,20.0,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [35]:
df.shape

(366, 22)

In [44]:
df.shape

(319, 22)

In [42]:
df.dropna(how='any',inplace=True)

In [43]:
df.isnull().sum()

MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RISK_MM          0
RainTomorrow     0
dtype: int64

In [45]:
df.dropna(how='any')

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,20.0,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No